### ISSUE TITLE
Improve the app design

### ISSUE THREAD

**Issue by haltakov** [underfitted/bnomial-frontend#3]
The goal of this item is to style the website in so it matches the design sketches by @dennys: fonts, colors, layout etc.

![image](https://user-images.githubusercontent.com/300777/151175577-339f1fa4-70db-4676-bc8b-7c01a706b3e0.png)

![image](https://user-images.githubusercontent.com/300777/151175622-931dcda9-5cd8-4bce-aa88-a7d99493b82e.png)

Related discussion here: https://discord.com/channels/909928541360123954/920191988211527691/920228967036887060

**Comment by kfischer-okarin** [comment]
There was also still a lot of feedback by @svpino which is mostly unaddressed/undiscussed yet since dennys was not available for a while...

https://discord.com/channels/909928541360123954/920191988211527691/920438091880222820

It might be good to first continue/finish that discussion before going in too deep?
